version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.41.0
    restart: always
    command: --storage.tsdb.retention.time=30d --web.enable-admin-api --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./data/prometheus:/prometheus"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:9.3.2
    environment:
      - GF_SERVER_ROOT_URL=https://gf.example.com
    restart: always
    volumes:
      - "./data/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
